### ISSUE TITLE
client could create donations by clicking "DONATIONS" at the slidebar menu

### ISSUE THREAD

**Issue by duskcloudxu** [FoodIsLifeBGP/banana-rn#146]
![image](https://user-images.githubusercontent.com/26619184/88966003-79c70180-d260-11ea-8ac2-fd092c627b9a.png)
![image](https://user-images.githubusercontent.com/26619184/88966088-9f540b00-d260-11ea-9f2c-068daf362660.png)

 clients could create donations by clicking that button and I guess it's unwanted behavior.

**Comment by tackc** [comment]
This no longer seems to be happening in the latest build of the app 😀
