### ISSUE TITLE
Windows Set-up Documentation

### ISSUE THREAD

**Issue by jacksonrya** [FoodIsLifeBGP/banana-rn#48]
There are two, old PRs (#26, #21) that update the README to include Windows setup instructions for the project.

@nexticodes mentioned that he wrote down some steps to get his set-up working.

Can we compare write-ups across all three, update the README and close those two old PRs?

**Comment by nexticodes** [comment]
I have a rough draft of the Windows setup documentation as well as the setup for Android Studio:

For development on Windows!! (Assuming backend is already set up)

**SETTING UP CODE ENVIRONMENT FOR WINDOWS**

Step 1) Go to [this website](https://github.com/coreybutler/nvm-windows) and follow the instructions for installing Node Version Manager for Windows 

***NOTE: This is necessary as the Banana app uses an older version of Node. This is also very convenient as it will let you switch between previous (or current) versions of Node depending on which project you're working on.***

Step 2) To confirm installation, open up your Command Prompt and run `nvm --version` and it should return the version of your NVM and a list of its usage.

Step 3) Once that's done, run `nvm install node@12.10.0` (Banana App's config are compatible with Node version <= 12.10.0) and Agree to all the prompts to complete installation.

Step 4) Run `nvm use 12.10.0` to make sure that your machine is using Node version 12.10.0. [NOTE: Run `nvm list` to see all the versions of Node that your NVM know and you can use the same command `nvm use [version]` to switch].

Step 5) Run `npm i -g expo-cli` to enable expo cli globally.

Step 6) Make sure you've traversed to the right directory (most likely Desktop) and run `git clone https://github.com/FoodIsLifeBGP/banana-rn && cd banana-rn && npm i`


**SETTING UP ANDROID SIMULATOR**

Step 1) Download the latest version of Android Studio [here](https://developer.android.com/studio/) and complete the installation. No other configurations needed.

Step 2) Once downloaded, open Android Studio and a little start up box should open. Go to the bottom right corner of that box and find "Configure" and select SDK manager.

Step 3) Under `Appearance & Behavior > System Settings > Android SDK settings` and SDK Platforms tab. Make sure you have Android 10.0 (Q) and Android 9.0(Pie) checked (also feel free to check  other Android versions, all up to your preference).

Step 4) Under the same settings / page, but on the SDK Tools Tab, Make sure you have Google Play and Android SDK Platform-Tools services checked and leave the rest untouched.

Step 5) Click "Apply" and "OK" to exit out.

Step 6) On the start up box, click on "Configure" one more time and select "AVD Manager". This AVD Manager shows you the list of Android emulators you have ready.

Step 7) To create a new device, simply click on "Create Virtual Device" at the bottom left.

Step 8) Select what kind of device you'd like to work with, but Pixel 2 does the job well and click "Next".

Step 9) Select which system image you want on the device. Simply hit the "Download" button next to the name and wait for it. Once downloaded, select it and hit "Next".

Step 10) Verify all the configurations (name, startup orientation, etc.) and click "Finish" when done.

Step 11) The configuration box will close and your new device should appear on your list of Virtual Devices. Select your choice, and click the green button under the "Actions" tab over on the right side of the window to launch the emulator.

**Comment by jacksonrya** [comment]
Wow! These are fantastic instructions and are much more thorough compared to the other open PRs. This is definitely going to improve the on-boarding process.

You wanna edit the README and update the master?

**Comment by nexticodes** [comment]
Thank you! Sure, I'll do it when I can!
