### ISSUE TITLE
[BUG] Misalignment in Dashboard (Android)

### ISSUE THREAD

**Issue by nexticodes** [FoodIsLifeBGP/banana-rn#74]
Hi everybody, I found a bug when I recently fetched from upstream to update my local files before pushing further changes I have made for my task.

This bug concerns the Dashboard (or perhaps just the NavBar component) and I have attached an image below showing where and what the misalignment is.

![Capture](https://user-images.githubusercontent.com/34993883/81099438-c5ffe100-8ebf-11ea-9052-23e58a44f5c7.JPG)

The NavBar has this x-offset that prevents Android users from accessing the hamburger menu that allows users to get to different areas of the app. Also it seems that the "+" sign that was supposed to be inside the circle is not there.

**Comment by jacksonrya** [comment]
This isn't a bug and is expected behavior.

Previously, a difficult-to-work-around padding was given to all screens. In order for the NavBar to show up properly atop all screens, the padding will be removed from each screen as needed.

see **breaking changes** section of #64

**Comment by jacksonrya** [comment]
As for the plus sign, the current design isn't full proof. A future `CircleButton`, or something like that, will replace this button and accept an icon name prop since there are a couple of places that use this button styling.

**Comment by nexticodes** [comment]
Thank you for the comments and clarification @jacksonrya !
